apiVersion: v1
kind: Service
metadata:
  name: {{ include "gawk-server.fullname" . }}
  labels:
    {{- include "gawk-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  selector:
    {{- include "gawk-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: webtransport
      port: {{ .Values.service.port }}
      targetPort: 4433
      protocol: UDP
