use std::path::Path;

fn main() {
    // The window itself, and the build revision it shows, are compiled and
    // stamped by gawk-ui (docs/54 D11): this script only links the icon.
    emit_icon_resource();
}

/// Links the application icon into the EXE as a Windows resource (R44,
/// docs/53 D7), which is what Explorer, a pinned taskbar shortcut and the
/// "unknown publisher" dialog read. The window's own icon is separate
/// (`Window.icon` in crates/ui/main.slint).
///
/// `assets/icon/gawk.res` is a compiled resource file generated by
/// `go run ./tools/icon generate` from the shared SVG and committed; both
/// lld-link (the cargo-xwin cross build, docs/38 D18) and MSVC link.exe take
/// a .res as a plain input, so no resource compiler — `rc.exe`, `llvm-rc`
/// or a crate wrapping one — is involved. msvc only: GNU ld would need
/// windres to convert it, and that target is a type-check, not a build.
/// broadcast-desktop.yml verifies the resource actually landed in the EXE.
fn emit_icon_resource() {
    println!("cargo::rerun-if-env-changed=CARGO_CFG_TARGET_OS");
    println!("cargo::rerun-if-env-changed=CARGO_CFG_TARGET_ENV");
    let os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if os != "windows" || env != "msvc" {
        return;
    }
    // Absolute via CARGO_MANIFEST_DIR, but NOT canonicalized: on a Windows
    // host canonicalize() yields a verbatim `\\?\C:\…` path, which link.exe
    // does not reliably accept (LNK1181) — rustc and the cc crate both strip
    // that prefix before invoking the linker for the same reason. The `..`
    // components are fine for lld-link and link.exe alike.
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let res = Path::new(&manifest).join("../../../assets/icon/gawk.res");
    assert!(
        res.exists(),
        "{} is missing — run `go run ./tools/icon generate`",
        res.display()
    );
    println!("cargo::rerun-if-changed={}", res.display());
    println!("cargo::rustc-link-arg-bins={}", res.display());
}
