#!/bin/sh
# Chooses and issues the certificate the local development stack presents
# (R38, docs/41 §4.3, §4.4, §4.6), and writes the .env that points the stack
# at it. Three lanes, one stack: everything downstream of ./certs is identical
# whichever you pick.
#
#   ./dev/certs.sh                 pick a lane interactively
#   ./dev/certs.sh devcert         self-signed, generated by the relay (default)
#   ./dev/certs.sh mkcert          a locally-trusted CA — Firefox works
#   ./dev/certs.sh acme            Let's Encrypt on a domain you control
#   ./dev/certs.sh renew           re-issue in the lane .env already names
#   ./dev/certs.sh check           run the preflight checks and report
#
# Two knobs come from the shell environment rather than .env (which is read
# key by key, not sourced): ACME_TXT_TIMEOUT, how long to wait for the
# challenge record before giving up without submitting (default 900 s — raise
# it when a person has to go and edit DNS), and ACME_TXT_POLL, how often to
# ask (default 10 s).
#
# This script never writes outside ./certs, ./dev/generated and ./.env, all of
# which are gitignored — a private key in a public repository is not a mistake
# with a warning attached, since CAs must revoke keys reported as compromised
# within 24 hours. It never echoes a DNS provider credential either.
set -eu

cd "$(dirname "$0")/.."
ROOT=$(pwd)
CERTS="$ROOT/certs"
ENV_FILE="$ROOT/.env"
CERT_PEM="$CERTS/cert.pem"
KEY_PEM="$CERTS/key.pem"

# Pinned, not :latest — an ACME client that changes under you is a bad
# surprise to have during an issuance (docs/41 D10 keeps it at arm's length
# from the relay's module graph entirely).
LEGO_IMAGE=${LEGO_IMAGE:-goacme/lego:v4}

# Set by the test harness so the wizard takes no input from a terminal.
NONINTERACTIVE=${GAWK_CERTS_NONINTERACTIVE:-}

say()  { printf '%s\n' "$*"; }
step() { printf '\n  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }
die()  { printf '\n  ✗ %s\n' "$*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# Reads one answer, or the default when there is no terminal to ask.
ask() { # ask <prompt> <default>
    _def=$2
    if [ -n "$NONINTERACTIVE" ] || [ ! -t 0 ]; then
        printf '%s\n' "$_def"
        return
    fi
    printf '  %s [%s] ' "$1" "$_def" >&2
    read -r _ans || _ans=
    [ -n "$_ans" ] || _ans=$_def
    printf '%s\n' "$_ans"
}

# ── .env ──────────────────────────────────────────────────────────────────
# Authored key by key so a developer's own edits and their provider
# credentials survive every re-run.

ensure_env() {
    if [ ! -f "$ENV_FILE" ]; then
        cp "$ROOT/.env.example" "$ENV_FILE"
        chmod 600 "$ENV_FILE"
        say "  wrote .env from .env.example"
    fi
}

env_get() { # env_get <key>
    [ -f "$ENV_FILE" ] || return 0
    sed -n "s/^$1=//p" "$ENV_FILE" | tail -1
}

env_set() { # env_set <key> <value>
    ensure_env
    _tmp="$ENV_FILE.tmp"
    if grep -q "^$1=" "$ENV_FILE" 2>/dev/null; then
        # The value can contain slashes and ampersands (URLs), so build the
        # replacement with awk rather than sed's substitution syntax.
        awk -v k="$1" -v v="$2" -F= '
            $1 == k && !done { print k "=" v; done = 1; next }
            { print }
        ' "$ENV_FILE" > "$_tmp"
    else
        cp "$ENV_FILE" "$_tmp"
        printf '%s=%s\n' "$1" "$2" >> "$_tmp"
    fi
    mv "$_tmp" "$ENV_FILE"
}

# Every lane writes these: who owns what the containers write into ./certs
# (so the host-binary inner loop can read the same key), and the addresses
# the stack and the browser agree on.
write_common_env() { # write_common_env <cert_mode> <dev_cert> <host> <app_port> <app_origin> <app_url> <relay_url> <profiles> <app_http_addr>
    env_set CERT_MODE "$1"
    env_set DEV_CERT "$2"
    env_set GAWK_HOST "$3"
    env_set APP_PORT "$4"
    env_set APP_ORIGIN "$5"
    env_set APP_URL "$6"
    env_set RELAY_URL "$7"
    env_set COMPOSE_PROFILES "$8"
    env_set APP_HTTP_ADDR "$9"
    env_set HOST_UID "$(id -u)"
    env_set HOST_GID "$(id -g)"
}

# ── DNS ───────────────────────────────────────────────────────────────────
# One place that shells out to a resolver, so the test harness can put a stub
# `dig` on PATH and drive every check from it.

dns_tool() {
    if have dig; then say dig
    elif have nslookup; then say nslookup
    else say ""
    fi
}

# dns_query <type> <name> [@server] → one answer per line, values unquoted
dns_query() {
    _type=$1 _name=$2 _server=${3:-}
    case "$(dns_tool)" in
        dig)
            # +short is the only output shape worth parsing; the trailing
            # dot and the quotes around TXT values are stripped by callers.
            if [ -n "$_server" ]; then
                dig +short +time=3 +tries=1 "$_type" "$_name" "@$_server" 2>/dev/null || true
            else
                dig +short +time=3 +tries=1 "$_type" "$_name" 2>/dev/null || true
            fi
            ;;
        nslookup)
            if [ -n "$_server" ]; then
                nslookup -type="$_type" "$_name" "$_server" 2>/dev/null | sed -n 's/.*text = //p;s/.*Address: //p' || true
            else
                nslookup -type="$_type" "$_name" 2>/dev/null | sed -n 's/.*text = //p;s/.*Address: //p' || true
            fi
            ;;
        *) return 0 ;;
    esac
}

# The nameservers actually authoritative for a zone. Asking them directly is
# what makes "still waiting…" honest: a public resolver's cached NXDOMAIN
# says nothing about whether the record exists yet.
authoritative_ns() { # authoritative_ns <domain>
    dns_query NS "$1" | sed 's/\.$//' | grep -v '^$' || true
}

# ── certificate inspection ────────────────────────────────────────────────
# openssl is used when it is on PATH and the check is skipped (loudly) when it
# is not: the default lane's whole claim is that Docker is the only
# prerequisite, and these checks belong to the lanes that already need more.

cert_field() { # cert_field <openssl-args…>
    [ -f "$CERT_PEM" ] || return 1
    have openssl || return 1
    openssl x509 -in "$CERT_PEM" -noout "$@" 2>/dev/null
}

cert_sans() {
    cert_field -ext subjectAltName | tr ',' '\n' | sed -n 's/.*DNS://p;s/.*IP Address://p' | tr -d ' '
}

cert_covers() { # cert_covers <host>
    _host=$1
    # An exact SAN, or the one-label wildcard that covers it: *.a.b matches
    # x.a.b and never y.x.a.b, which is the rule browsers apply.
    cert_sans | grep -qxF "$_host" && return 0
    case "$_host" in
        *.*) cert_sans | grep -qxF "*.${_host#*.}" ;;
        *)   return 1 ;;
    esac
}

# ── preflight (docs/41 §4.6) ──────────────────────────────────────────────

check_expiry() {
    _not_after=$(cert_field -enddate | sed 's/notAfter=//') || {
        warn "expiry not checked (no openssl on PATH)"
        return 0
    }
    [ -n "$_not_after" ] || return 0
    _mode=$(env_get CERT_MODE); _mode=${_mode:-devcert}
    # 72 h in the default lane — a 14-day certificate that regenerates for
    # free — and 30 days for the trusted lanes, where replacing it is work
    # and, in the manual ACME sub-lane, cannot happen by itself at all.
    if [ "$_mode" = "devcert" ]; then _win=$((72 * 3600)); _label="72 hours"
    else _win=$((30 * 86400)); _label="30 days"; fi

    if have openssl && ! openssl x509 -in "$CERT_PEM" -noout -checkend "$_win" >/dev/null 2>&1; then
        warn "the certificate expires within $_label (not after: $_not_after)"
        warn "  → ./dev/certs.sh renew"
    else
        say "  certificate valid until $_not_after"
    fi

    # A backdated certificate fails validation in a way nothing else explains,
    # and a container clock that has drifted is the usual cause.
    if have openssl && ! openssl x509 -in "$CERT_PEM" -noout -checkend 0 >/dev/null 2>&1; then
        warn "the certificate is not valid yet or has expired — check this machine's clock (notBefore/notAfter vs. $(date -u '+%Y-%m-%dT%H:%M:%SZ'))"
    fi
}

check_covers_host() {
    _host=$(env_get GAWK_HOST); _host=${_host:-localhost}
    [ -f "$CERT_PEM" ] || { say "  no certificate yet (the relay writes one on first start in the devcert lane)"; return 0; }
    have openssl || { warn "SANs not checked (no openssl on PATH)"; return 0; }
    if cert_covers "$_host"; then
        say "  certificate covers $_host"
    else
        warn "the certificate does NOT cover $_host — the browser would fail with an opaque error"
        warn "  SANs: $(cert_sans | tr '\n' ' ')"
        warn "  → ./dev/certs.sh $(env_get CERT_MODE), or set GAWK_HOST in .env to a name it covers"
        return 1
    fi
}

# Docker is the thing that will actually fail to bind, so ask Docker. Needs no
# lsof/ss/netstat, and reports exactly the conflict that would stop `up`.
check_port_free() { # check_port_free <bind> <port> <proto> <env-var>
    have docker || return 0
    if docker run --rm -p "$1:$2:$2/$3" alpine:3.21 true >/dev/null 2>&1; then
        say "  $2/$3 is free"
    else
        warn "$2/$3 on $1 is already in use — change $4 in .env"
        return 1
    fi
}

preflight() {
    step "Preflight"
    _rc=0
    check_expiry || _rc=1
    check_covers_host || _rc=1

    # A port the stack itself is holding is not a conflict — checking it while
    # it is up would report every running stack as broken.
    if have docker && [ -n "$(docker compose ps --status running --services 2>/dev/null)" ]; then
        say "  ports not checked (this stack is already up)"
        return $_rc
    fi
    _bind=$(env_get BIND_ADDR); _bind=${_bind:-127.0.0.1}
    _app_addr=$(env_get APP_HTTP_ADDR); _app_addr=${_app_addr:-127.0.0.1:8080}
    check_port_free "${_app_addr%:*}" "${_app_addr##*:}" tcp APP_HTTP_ADDR || _rc=1
    _relay_port=$(env_get RELAY_PORT); _relay_port=${_relay_port:-4433}
    check_port_free "$_bind" "$_relay_port" udp RELAY_PORT || _rc=1
    return $_rc
}

# ── LAN exposure ──────────────────────────────────────────────────────────

# Never a Docker bridge address, and never a silent guess: the wizard asks
# when detection is ambiguous (docs/41 §4.7).
detect_lan_ip() {
    _ips=""
    case "$(uname -s)" in
        Darwin)
            for _if in $(ipconfig getiflist 2>/dev/null || echo "en0 en1"); do
                _ip=$(ipconfig getifaddr "$_if" 2>/dev/null || true)
                [ -n "$_ip" ] && _ips="$_ips $_ip"
            done
            ;;
        *)
            if have ip; then
                _ips=$(ip -4 -o addr show scope global 2>/dev/null \
                    | grep -vE ' (docker|br-|veth|virbr)' \
                    | awk '{print $4}' | cut -d/ -f1 | tr '\n' ' ')
            fi
            ;;
    esac
    # Docker's default pools are 172.17–172.31; a LAN address there would be
    # unreachable from the phone this option exists for.
    for _ip in $_ips; do
        case "$_ip" in
            172.1[7-9].*|172.2[0-9].*|172.3[01].*|127.*) continue ;;
        esac
        printf '%s\n' "$_ip"
    done
}

choose_lan_ip() {
    _found=$(detect_lan_ip | tr '\n' ' ')
    _count=$(printf '%s' "$_found" | wc -w | tr -d ' ')
    if [ "$_count" = "1" ]; then
        ask "This machine's LAN address?" "$(printf '%s' "$_found" | tr -d ' ')"
    else
        [ "$_count" = "0" ] || say "  candidates: $_found"
        ask "This machine's LAN address? (empty = keep the stack on this machine)" ""
    fi
}

# ── lane A: the relay's own self-signed certificate ───────────────────────

lane_devcert() {
    step "Lane: self-signed, generated once and persisted (no prerequisites)"
    ensure_env
    _lan=$(env_get LAN_IP)
    if [ -z "$_lan" ] && [ -z "$NONINTERACTIVE" ]; then
        _lan=$(choose_lan_ip)
    fi
    _hosts="localhost,127.0.0.1"
    _bind="127.0.0.1"
    if [ -n "$_lan" ]; then
        _hosts="$_hosts,$_lan"
        _bind="0.0.0.0"
        say "  including $_lan in the certificate and exposing the stack to your LAN"
        say "  (other devices still need the hash — a trusted lane is the better answer there)"
    fi
    env_set LAN_IP "$_lan"
    env_set BIND_ADDR "$_bind"
    env_set CERT_HOSTS "$_hosts"
    write_common_env devcert 1 localhost 8080 \
        "http://localhost:8080" "http://localhost:8080" "https://127.0.0.1:4433" "" "$_bind:8080"

    # The relay generates on first start; if a pair is already there for a
    # different set of names, say so rather than leaving it to the browser.
    if [ -f "$CERT_PEM" ] && have openssl; then
        say "  keeping the existing pair in ./certs (delete it, or ./dev/certs.sh renew, to reissue)"
    fi
    say ""
    say "  Ready. Start it with:   docker compose up"
    say "  Then open:              http://localhost:8080"
}

# ── lane B: mkcert ────────────────────────────────────────────────────────

mkcert_install_hint() {
    case "$(uname -s)" in
        Darwin) say "  brew install mkcert nss   # nss is what makes Firefox trust it" ;;
        Linux)  say "  see https://github.com/FiloSottile/mkcert#installation (apt: libnss3-tools + the mkcert release binary)" ;;
        *)      say "  see https://github.com/FiloSottile/mkcert#installation" ;;
    esac
}

lane_mkcert() {
    step "Lane: mkcert — a locally-trusted CA, so Firefox works and no hash is involved"
    have mkcert || {
        warn "mkcert is not on PATH. Install it (this script deliberately does not):"
        mkcert_install_hint
        exit 1
    }
    ensure_env
    _lan=$(env_get LAN_IP)
    if [ -z "$_lan" ] && [ -z "$NONINTERACTIVE" ]; then
        _lan=$(choose_lan_ip)
    fi

    # Idempotent, and the only step that can raise an admin prompt — once per
    # machine, not once per run. Writing the system trust store needs that
    # password, and a lane whose whole point is a TRUSTED certificate must not
    # continue without it: the stack would come up and fail in the browser
    # with an error naming nothing.
    say "  installing the local CA (no-op if it is already there)"
    if ! mkcert -install; then
        warn ""
        warn "mkcert could not write the trust store. That step needs an administrator"
        warn "  password, which it can only ask for from a terminal. Run it yourself and"
        warn "  then re-run this script:"
        warn ""
        warn "      mkcert -install"
        warn ""
        warn "  For Firefox only — no password needed, since Firefox keeps its own store:"
        warn ""
        warn "      TRUST_STORES=nss mkcert -install"
        exit 1
    fi

    mkdir -p "$CERTS"
    say "  issuing for gawk.localhost, *.gawk.localhost, localhost, 127.0.0.1, ::1${_lan:+, $_lan}"
    # shellcheck disable=SC2086
    mkcert -cert-file "$CERT_PEM" -key-file "$KEY_PEM" \
        gawk.localhost "*.gawk.localhost" localhost 127.0.0.1 ::1 ${_lan:+$_lan}
    chmod 600 "$KEY_PEM"

    _bind="127.0.0.1"
    [ -n "$_lan" ] && _bind="0.0.0.0"
    env_set LAN_IP "$_lan"
    env_set BIND_ADDR "$_bind"
    # The RELAY url is an IP literal on purpose: gawk.localhost resolves to
    # ::1 as well as 127.0.0.1 in both Chromium and Firefox, Docker publishes
    # the relay's UDP port on IPv4 only, and a QUIC dial has none of the TCP
    # fallback that hides this for the app's port.
    _relay_host=${_lan:-127.0.0.1}
    write_common_env mkcert "" gawk.localhost 8443 \
        "https://gawk.localhost:8443" "https://gawk.localhost:8443" \
        "https://$_relay_host:4433" tls "127.0.0.1:8081"

    say ""
    say "  Ready. Start it with:   docker compose up"
    say "  Then open:              https://gawk.localhost:8443"
    say ""
    say "  Other devices need this machine's mkcert root installed:"
    say "    $(mkcert -CAROOT)/rootCA.pem"
    say "  If that is the point, the ACME lane is the one that needs nothing installed."
}

# ── lane C: ACME on a domain you control ──────────────────────────────────

acme_intro() {
    step "Lane: Let's Encrypt on a domain you control (DNS-01, one wildcard)"
    say ""
    say "  DNS-01 proves control of the NAME, not reachability of the HOST."
    say "  Every A record you add points at 127.0.0.1 (or your LAN address)."
    say "  Nothing about this machine is exposed to the internet."
}

# CAA before issuance, not after a failed one: a forbidden CAA record fails
# every attempt identically, and failed validations are rate-limited.
check_caa() { # check_caa <domain>
    _domain=$1
    [ -n "$(dns_tool)" ] || { warn "CAA not checked (no dig/nslookup on PATH)"; return 0; }
    _caa=$(dns_query CAA "$_domain" | grep -i issue || true)
    if [ -z "$_caa" ]; then
        say "  CAA on $_domain: none (any CA may issue)"
        return 0
    fi
    if printf '%s' "$_caa" | grep -qi 'letsencrypt.org'; then
        say "  CAA on $_domain: Let's Encrypt permitted"
        return 0
    fi
    warn "CAA on $_domain forbids Let's Encrypt:"
    printf '      %s\n' "$_caa" >&2
    warn "  Add   $_domain. CAA 0 issue \"letsencrypt.org\"   (and issuewild for a wildcard),"
    warn "  or use a domain without that restriction. Not spending an issuance on this."
    return 1
}

# Poll the authoritative nameservers until every one of them serves the
# challenge value. Submitting before propagation is the classic failure here,
# and Let's Encrypt rate-limits FAILED validations at 5/hour — an impatient
# run locks you out for an hour with no explanation.
wait_for_txt() { # wait_for_txt <fqdn> <value> <domain>
    _fqdn=$1 _value=$2 _domain=$3
    _ns=$(authoritative_ns "$_domain")
    [ -n "$_ns" ] || { warn "no authoritative nameserver found for $_domain — waiting on the default resolver instead"; _ns=""; }
    _waited=0
    while :; do
        _seen=1
        if [ -n "$_ns" ]; then
            for _server in $_ns; do
                if ! dns_query TXT "$_fqdn" "$_server" | tr -d '"' | grep -qxF "$_value"; then
                    _seen=0
                fi
            done
        else
            dns_query TXT "$_fqdn" | tr -d '"' | grep -qxF "$_value" || _seen=0
        fi
        if [ "$_seen" = "1" ]; then
            say "  ✓ seen on every authoritative nameserver after ${_waited}s — validating"
            return 0
        fi
        if [ "$_waited" -ge "${ACME_TXT_TIMEOUT:-900}" ]; then
            warn "the TXT record never appeared after ${_waited}s. Nothing was submitted, so no rate limit was spent."
            return 1
        fi
        printf '  still waiting… (%ss elapsed — normally 1–5 min, safe to leave running)\r' "$_waited" >&2
        sleep "${ACME_TXT_POLL:-10}"
        _waited=$((_waited + ${ACME_TXT_POLL:-10}))
    done
}

# Let's Encrypt's failure modes are obscure enough that naming them is most of
# this lane's value.
explain_acme_failure() { # explain_acme_failure <log-file>
    _log=$1
    if grep -qi 'too many failed authorizations' "$_log" 2>/dev/null; then
        warn "Let's Encrypt rate limit: too many FAILED validations (5 per hour, per account and hostname)."
        warn "  It clears an hour after the first failure. Fix the DNS record before retrying —"
        warn "  another attempt now only pushes the window out."
    elif grep -qi 'too many certificates' "$_log" 2>/dev/null; then
        warn "Let's Encrypt rate limit: too many certificates issued (50 per registered domain per week,"
        warn "  and 5 duplicates of the identical name set per week). Set ACME_STAGING=1 in .env to"
        warn "  rehearse against the staging endpoint, which has far larger limits."
    elif grep -qi 'could not find zone' "$_log" 2>/dev/null; then
        warn "lego could not work out which DNS zone to write the challenge into. That walk is"
        warn "  SOA queries, and the resolver it used did not answer them. Set LEGO_DNS_RESOLVERS"
        warn "  in .env to a recursive resolver you can reach (default: 1.1.1.1:53,8.8.8.8:53)."
    elif grep -qi 'urn:ietf:params:acme:error:unauthorized' "$_log" 2>/dev/null; then
        warn "Let's Encrypt could not see the challenge record. The usual cause is a TXT record added"
        warn "  in the wrong zone, or a CNAME'd _acme-challenge pointing somewhere unexpected."
    fi
}

# The name the stack will serve, resolved the way a browser will resolve it.
# A resolver with DNS-rebinding protection refuses to return 127.0.0.1 (or an
# RFC1918 address) from public DNS, and the symptom is a name that simply does
# not resolve — while the authoritative server answers correctly.
check_rebinding() { # check_rebinding <fqdn> <domain>
    _fqdn=$1 _domain=$2
    [ -n "$(dns_tool)" ] || return 0
    _local=$(dns_query A "$_fqdn" | grep -E '^[0-9.]+$' || true)
    [ -n "$_local" ] && { say "  $_fqdn resolves to $_local"; return 0; }

    _ns=$(authoritative_ns "$_domain" | head -1)
    _auth=""
    [ -n "$_ns" ] && _auth=$(dns_query A "$_fqdn" "$_ns" | grep -E '^[0-9.]+$' || true)
    if [ -n "$_auth" ]; then
        warn "$_fqdn resolves to $_auth authoritatively but to nothing here — your resolver has"
        warn "  DNS-rebinding protection, which drops loopback/private answers from public DNS."
        warn "  Add this line to /etc/hosts:"
        warn ""
        warn "      $_auth  $_fqdn"
    else
        warn "$_fqdn does not resolve yet. Add an A record for it (pointing at 127.0.0.1, or at"
        warn "  this machine's LAN address for other devices) — the certificate already covers it."
    fi
}

# Every .env variable that is not one of ours, handed to lego so any of its
# ~100 DNS providers works. Written to a 0600 temp file and removed on exit;
# the values are never printed.
lego_env_file() {
    _f=$(mktemp)
    chmod 600 "$_f"
    grep -E '^[A-Z][A-Z0-9_]*=' "$ENV_FILE" 2>/dev/null \
        | grep -vE '^(CERT_MODE|DEV_CERT|GAWK_HOST|APP_PORT|APP_URL|APP_ORIGIN|APP_HTTP_ADDR|RELAY_PORT|RELAY_URL|BIND_ADDR|CERT_HOSTS|LAN_IP|HOST_UID|HOST_GID|LOG_LEVEL|COMPOSE_PROFILES|GAWK_TELEMETRY_KEY|ACME_DOMAIN|ACME_SUBDOMAIN|ACME_EMAIL|ACME_STAGING|LEGO_DNS_PROVIDER)=' \
        > "$_f" || true
    printf '%s\n' "$_f"
}

lego_args() { # lego_args <wildcard> <email> <staging>
    printf '%s\n' "--accept-tos" "--email=$2" "--domains=$1" "--path=/certs/lego"
    # lego finds the zone to write into by walking up the name with SOA
    # queries, and Docker's embedded resolver (127.0.0.11) does not answer
    # those: it walks to the TLD, gets NOERROR with no SOA, and fails before
    # it ever prints a challenge record. Pointing it at real recursive
    # resolvers is the fix — configurable, because a machine behind a
    # filtering network may need its own.
    printf '%s\n' "--dns.resolvers=${LEGO_DNS_RESOLVERS:-1.1.1.1:53,8.8.8.8:53}"
    [ "$3" = "1" ] && printf '%s\n' "--server=https://acme-staging-v02.api.letsencrypt.org/directory"
    return 0
}

# lego writes certs/lego/certificates/<name>.crt|.key; the stack reads
# certs/cert.pem and certs/key.pem, so link the two here rather than teaching
# every service where lego happens to put things.
install_lego_output() { # install_lego_output <wildcard>
    _safe=$(printf '%s' "$1" | sed 's/^\*/_/')
    _crt="$CERTS/lego/certificates/$_safe.crt"
    _key="$CERTS/lego/certificates/$_safe.key"
    [ -f "$_crt" ] || _crt=$(ls -t "$CERTS"/lego/certificates/*.crt 2>/dev/null | head -1 || true)
    [ -f "$_key" ] || _key=$(ls -t "$CERTS"/lego/certificates/*.key 2>/dev/null | head -1 || true)
    [ -n "$_crt" ] && [ -f "$_crt" ] || die "lego produced no certificate"
    cp "$_crt" "$CERT_PEM"
    cp "$_key" "$KEY_PEM"
    chmod 644 "$CERT_PEM"
    chmod 600 "$KEY_PEM"
    say "  → certs/cert.pem, certs/key.pem"
}

# C-1: the provider has an API, so lego does the whole dance — and renewal
# needs no human at all.
acme_run_api() { # acme_run_api <wildcard> <email> <staging> <provider> <renew?>
    _wildcard=$1 _email=$2 _staging=$3 _provider=$4 _renew=${5:-}
    _envf=$(lego_env_file)
    _log=$(mktemp)
    # shellcheck disable=SC2064
    trap "rm -f '$_envf' '$_log'" EXIT INT TERM

    if [ -n "$_renew" ]; then _verb="renew --days 30"; else _verb="run"; fi
    say "  running lego with the $_provider provider (credentials come from .env and are never printed)"
    # shellcheck disable=SC2046,SC2086
    if docker run --rm --env-file "$_envf" -v "$CERTS:/certs" "$LEGO_IMAGE" \
        $(lego_args "$_wildcard" "$_email" "$_staging") --dns "$_provider" $_verb \
        > "$_log" 2>&1; then
        sed 's/^/    /' "$_log"
        _rc=0
    else
        sed 's/^/    /' "$_log" >&2
        explain_acme_failure "$_log"
        _rc=1
    fi
    rm -f "$_envf" "$_log"
    trap - EXIT INT TERM
    return $_rc
}

# C-2: no API. lego prints a TXT record and waits on stdin; the wizard reads
# the record out of its output, polls the authoritative nameservers itself,
# and only then lets lego proceed. That is the whole point of this lane —
# anyone can link the certbot docs; naming the failure is the value.
acme_run_manual() { # acme_run_manual <wildcard> <email> <staging> <domain> <sub>
    _wildcard=$1 _email=$2 _staging=$3 _domain=$4 _sub=$5
    _log=$(mktemp)
    _fifo=$(mktemp -u)
    mkfifo "$_fifo"
    # shellcheck disable=SC2064
    trap "rm -f '$_log' '$_fifo'" EXIT INT TERM

    # Hold the write end open so lego's stdin does not see EOF before we are
    # ready to let it proceed. Opened read-WRITE deliberately: opening a fifo
    # write-only blocks until a reader attaches, which is a deadlock when the
    # reader is the process we have not started yet.
    exec 9<>"$_fifo"
    # shellcheck disable=SC2046,SC2086
    docker run --rm -i -v "$CERTS:/certs" "$LEGO_IMAGE" \
        $(lego_args "$_wildcard" "$_email" "$_staging") --dns manual run \
        < "$_fifo" > "$_log" 2>&1 &
    _lego=$!

    _fqdn="_acme-challenge.$_sub.$_domain"
    _value=""
    _waited=0
    while [ -z "$_value" ]; do
        # lego prints the record as a zone line; take the quoted value from
        # whichever line names the challenge.
        _value=$(grep "_acme-challenge" "$_log" 2>/dev/null | sed -n 's/.*"\([^"]*\)".*/\1/p' | tail -1 || true)
        if [ -z "$_value" ]; then
            _value=$(grep -A2 "_acme-challenge" "$_log" 2>/dev/null | sed -n 's/^[[:space:]]*\([A-Za-z0-9_-]\{20,\}\)[[:space:]]*$/\1/p' | tail -1 || true)
        fi
        [ -n "$_value" ] && break
        kill -0 "$_lego" 2>/dev/null || break
        [ "$_waited" -ge 120 ] && break
        sleep 2
        _waited=$((_waited + 2))
    done

    if [ -z "$_value" ]; then
        exec 9>&-
        wait "$_lego" || true
        sed 's/^/    /' "$_log" >&2
        explain_acme_failure "$_log"
        die "could not read the challenge value out of lego's output"
    fi

    say ""
    say "  Add this TXT record at your DNS host:"
    say ""
    say "      name   $_fqdn"
    say "      type   TXT"
    say "      value  $_value"
    say ""
    say "  Waiting for it to appear on the authoritative nameservers…"
    if ! wait_for_txt "$_fqdn" "$_value" "$_domain"; then
        exec 9>&-
        kill "$_lego" 2>/dev/null || true
        wait "$_lego" 2>/dev/null || true
        die "gave up before submitting — nothing was sent to Let's Encrypt"
    fi

    # Only now does lego get to proceed.
    printf '\n' >&9
    exec 9>&-
    if wait "$_lego"; then
        sed 's/^/    /' "$_log"
        return 0
    fi
    sed 's/^/    /' "$_log" >&2
    explain_acme_failure "$_log"
    return 1
}

lane_acme() { # lane_acme [renew]
    _renew=${1:-}
    acme_intro
    ensure_env

    _domain=$(env_get ACME_DOMAIN)
    [ -n "$_domain" ] || _domain=$(ask "Domain you control?" "")
    [ -n "$_domain" ] || die "a domain is required for this lane"
    _sub=$(env_get ACME_SUBDOMAIN); _sub=${_sub:-dev}
    [ -n "$NONINTERACTIVE" ] || _sub=$(ask "Subdomain for local dev?" "$_sub")
    _email=$(env_get ACME_EMAIL)
    [ -n "$_email" ] || _email=$(ask "Let's Encrypt account email?" "")
    [ -n "$_email" ] || die "Let's Encrypt needs an account email"
    _staging=$(env_get ACME_STAGING); _staging=${_staging:-0}
    _provider=$(env_get LEGO_DNS_PROVIDER)

    env_set ACME_DOMAIN "$_domain"
    env_set ACME_SUBDOMAIN "$_sub"
    env_set ACME_EMAIL "$_email"

    _wildcard="*.$_sub.$_domain"
    _host="gawk.$_sub.$_domain"
    say "  → will request a wildcard for $_wildcard"
    [ "$_staging" = "1" ] && say "  → Let's Encrypt STAGING (the certificate will not be trusted)"

    check_caa "$_domain" || exit 1

    mkdir -p "$CERTS/lego"
    if [ -n "$_provider" ]; then
        acme_run_api "$_wildcard" "$_email" "$_staging" "$_provider" "${_renew:+1}" || exit 1
    else
        [ -z "$_renew" ] || warn "the manual sub-lane cannot renew by itself — reissuing instead"
        acme_run_manual "$_wildcard" "$_email" "$_staging" "$_domain" "$_sub" || exit 1
    fi
    install_lego_output "$_wildcard"

    _lan=$(env_get LAN_IP)
    _bind="127.0.0.1"
    [ -n "$_lan" ] && _bind="0.0.0.0"
    env_set BIND_ADDR "$_bind"
    write_common_env acme "" "$_host" 8443 \
        "https://$_host:8443" "https://$_host:8443" "https://$_host:4433" tls "127.0.0.1:8081"

    say ""
    say "  Now add A records for whatever you want to reach:"
    say ""
    say "      $_host   A  127.0.0.1"
    [ -n "$_lan" ] && say "      lan.$_sub.$_domain   A  $_lan   ← this machine's LAN address"
    say ""
    check_rebinding "$_host" "$_domain"
    if [ -z "$_provider" ]; then
        say ""
        warn "This sub-lane cannot renew automatically — there is no DNS API to answer the next"
        warn "  challenge with. Run ./dev/certs.sh acme again before it expires."
    fi
    say ""
    say "  Then: docker compose up   and open https://$_host:8443"
}

# ── renew ─────────────────────────────────────────────────────────────────

lane_renew() {
    _mode=$(env_get CERT_MODE); _mode=${_mode:-devcert}
    case "$_mode" in
        devcert)
            step "Renewing the self-signed pair"
            # The relay regenerates when NEITHER file is present; removing
            # only one is the case it deliberately refuses.
            rm -f "$CERT_PEM" "$KEY_PEM"
            say "  removed ./certs/cert.pem and ./certs/key.pem"
            say "  the relay writes a fresh pair on its next start:  docker compose up -d --force-recreate relay"
            ;;
        mkcert) lane_mkcert ;;
        acme)   lane_acme renew ;;
        *)      die "unknown CERT_MODE=$_mode in .env" ;;
    esac
}

# ── main ──────────────────────────────────────────────────────────────────

choose_lane() {
    say ""
    say "  Which certificate should the relay present?"
    say ""
    say "    1  self-signed, generated once and persisted  (nothing to install, works offline)"
    say "    2  mkcert — a locally-trusted CA              (one admin prompt; Firefox works)"
    say "    3  Let's Encrypt on a domain you control      (other devices join with nothing installed)"
    say ""
    case "$(ask "Pick" "1")" in
        2|mkcert) say mkcert ;;
        3|acme)   say acme ;;
        *)        say devcert ;;
    esac
}

main() {
    case "${1:-}" in
        devcert|mkcert|acme) _lane=$1 ;;
        renew) lane_renew; exit 0 ;;
        check) ensure_env; preflight; exit $? ;;
        -h|--help|help)
            # The header block, to the first line that is not a comment — so
            # help cannot drift out of step with what the file says.
            awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "$0"
            exit 0
            ;;
        "")
            _lane=$(env_get CERT_MODE)
            if [ -z "$NONINTERACTIVE" ]; then _lane=$(choose_lane); fi
            _lane=${_lane:-devcert}
            ;;
        *) die "unknown command: $1 (try --help)" ;;
    esac

    case "$_lane" in
        devcert) lane_devcert ;;
        mkcert)  lane_mkcert ;;
        acme)    lane_acme ;;
        *)       die "unknown lane: $_lane" ;;
    esac
    preflight || true
}

main "$@"
