#!/bin/sh
# Renders the local stack's /config.js (R38, docs/41 §4.2.2).
#
# This is the same runtime-configuration mechanism the gawk-app Helm chart
# uses — a file that sets window.__GAWK_CONFIG__ before the bundle runs — so
# the frontend needs no dev-only code path. It runs in the `config-gen`
# service, after the relay reports healthy, and exits.
#
# Inputs (environment): RELAY_URL, APP_URL, CERT_MODE, OUT.
set -eu

CERT=${CERT:-/certs/cert.pem}
OUT=${OUT:-/out/config.js}
CERT_MODE=${CERT_MODE:-devcert}
RELAY_URL=${RELAY_URL:-https://localhost:4433}
APP_URL=${APP_URL:-http://localhost:8080}

# The relay is healthy, so the pair exists — but poll rather than assume, and
# fail loudly rather than emit a config with no hash in it, which would fail
# later in a browser with an opaque certificate error instead.
waited=0
while [ ! -f "$CERT" ]; do
    if [ "$waited" -ge 30 ]; then
        echo "config-gen: $CERT never appeared; the relay did not write a certificate" >&2
        exit 1
    fi
    sleep 1
    waited=$((waited + 1))
done

# The hash the browser wants is hex SHA-256 of the certificate DER — the same
# value the relay logs as cert_hash_hex, and NOT the SPKI fingerprint (base64,
# and only for the Chrome launch flag).
#
# Computed with busybox rather than openssl: the alpine base image carries no
# openssl binary (verified on alpine:3.21), and installing one would need the
# network in a lane whose whole claim is that it works offline. PEM is just
# base64-wrapped DER, so the leaf block decodes to exactly the bytes to hash.
cert_hash_hex() {
    awk '/-----BEGIN CERTIFICATE-----/ {f=1; next}
         /-----END CERTIFICATE-----/   {exit}
         f' "$CERT" | base64 -d | sha256sum | cut -d' ' -f1
}

HASH=
if [ "$CERT_MODE" = "devcert" ]; then
    HASH=$(cert_hash_hex)
    if [ -z "$HASH" ]; then
        echo "config-gen: could not compute the certificate hash from $CERT" >&2
        exit 1
    fi
fi

# Written atomically: the app serves this file, and a half-written config.js
# is a syntax error in the page rather than a missing value.
TMP="$OUT.tmp"
{
    echo "// Generated by dev/config-gen.sh — do not edit. Regenerated on every \`up\`."
    echo "window.__GAWK_CONFIG__ = {"
    echo "  relayUrl: \"$RELAY_URL\","
    # Required, not decorative: requiresPublishSecret() falls back to
    # isDevEnvironment(), which is true on localhost, so omitting this makes
    # the broadcaster prompt for a secret this stack never configured.
    echo "  requirePublishSecret: false,"
    if [ -n "$HASH" ]; then
        # Dev-only key (docs/41 D4), and the reason the chrome-free
        # #/view/{id} route works here in a fresh profile.
        echo "  devCertHashHex: \"$HASH\","
    fi
    echo "};"
} > "$TMP"
mv "$TMP" "$OUT"

echo "config-gen: wrote $OUT (relay $RELAY_URL, mode $CERT_MODE${HASH:+, cert ${HASH}})"
echo ""
echo "    gawk is up — open $APP_URL"
echo ""
