// gawk-app has no library build (private app package, no `dist/` entry, no
// shipped .d.ts). This generates the two inputs the converter needs, both
// derived from cfg.componentSrcMap so they can never drift from the config:
//
//   .ds-entry.ts  - esbuild's bundle entry (value re-exports of every component)
//   index.d.ts    - the types entry projectFor() looks for at <pkgDir>/index.d.ts,
//                   re-exporting the tsc-emitted tree under .ds-types/
//
// Both are gitignored build artifacts. See .design-sync/NOTES.md.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const cfg = JSON.parse(readFileSync(new URL('./config.json', import.meta.url), 'utf8'));
const map = cfg.componentSrcMap ?? {};

// Group component names by source file so one-file-many-exports (Icons.tsx)
// emits a single re-export statement.
const byPath = new Map();
for (const [name, path] of Object.entries(map)) {
  if (path === null) continue;
  const mod = './' + path.replace(/\.(tsx|ts|jsx|js)$/, '');
  if (!byPath.has(mod)) byPath.set(mod, []);
  byPath.get(mod).push(name);
}

// Non-component exports the authored previews need in order to render a
// component truthfully (e.g. a zustand store whose default state makes the
// component return null). These are hooks/stores, so the converter's
// isComponentName filter keeps them out of the component list — they just ride
// along on window.<globalName> for the previews to drive.
const supportPath = new URL('./preview-support-exports.json', import.meta.url);
const support = existsSync(supportPath) ? JSON.parse(readFileSync(supportPath, 'utf8')).exports ?? {} : {};
for (const [path, names] of Object.entries(support)) {
  const mod = './' + path.replace(/\.(tsx|ts|jsx|js)$/, '');
  byPath.set(mod, [...(byPath.get(mod) ?? []), ...names]);
}

const lines = [...byPath.entries()]
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([mod, names]) => `export { ${names.sort().join(', ')} } from ${JSON.stringify(mod)};`);

const banner = '// GENERATED by .design-sync/gen-entry.mjs - do not edit, do not commit.\n';
writeFileSync('.ds-entry.ts', banner + lines.join('\n') + '\n');

// The declaration tree is emitted to .ds-types/ mirroring the package root, so
// the barrel's declarations land at .ds-types/.ds-entry.d.ts.
writeFileSync('index.d.ts', banner + `export * from './.ds-types/.ds-entry';\n`);

console.log(`wrote .ds-entry.ts (${byPath.size} modules, ${[...byPath.values()].flat().length} exports) + index.d.ts`);
